version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "atmdb"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
    ports:
      - "5436:5432"



#version: '3.7'
#
#services:
#  pg_db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=testdb
#      - POSTGRES_USER=db
#      - POSTGRES_PASSWORD=db
#    volumes:
#      - db:/var/lib/postgresql/data
#    ports:
#      - "5435:5432"
#
#volumes:
#  db: